### ISSUE TITLE
Change Node 16 moduleResolution to "Node16"

### ISSUE THREAD

**Issue by luis815** [tsconfig/bases#121]
## Issue
Current moduleResolution value is "node". This doesn't seem to support "exports" in package.json.

## Possible Solution
Change moduleResolution to "Node16" seems appropriate. A quick test overriding the value after extending this configuration seems to solve the issue.

**Comment by voxpelli** [comment]
+1 on a `node16+esm` if the main one can't have it

**Comment by orta** [comment]
Sure thing, add it

**Comment by Gerrit0** [comment]
> when people might expect esm projects to be the default

If module is set to commonjs, moduleResolution can be set to node16 to allow import/export maps to work properly while still emitting cjs

**Comment by Gerrit0** [comment]
Actually, that seems to not even be required.

https://www.typescriptlang.org/tsconfig#module

I'm using node16 in the beta branch for TypeDoc and am getting cjs output as expected.

**Comment by bradennapier** [comment]
In typescript 5.2 it is an error to have `moduleResolution` set to `node` so we will need a separate `esm` vs `cjs` option. 

Currently with 5.2 the `node18` base config does not work.  It requires you add `Node16` as `moduleResolution` which will force `esm` support which makes it impossible to use with our project.

Looks like `module` will need to change 

https://devblogs.microsoft.com/typescript/announcing-typescript-5-2-beta/#module-and-moduleresolution-must-match-under-recent-node-js-settings

**Comment by orta** [comment]
This happened in https://github.com/tsconfig/bases/pull/197
