### ISSUE TITLE
Deno base not published to npm

### ISSUE THREAD

**Issue by hkatzdev** [tsconfig/bases#13]
Deno base is not published to npm according to https://www.npmjs.com/search?q=%40tsconfig.

**Comment by orta** [comment]
Deploys happen overnight, looks like this deploy failed https://github.com/tsconfig/bases/runs/715486558?check_suite_focus=true#step:6:1

**Comment by orta** [comment]
OK, that's now deployed and I'm pretty certain the scheduled deploy system should work
