### ISSUE TITLE
@tsconfig/next-strictest does not exist

### ISSUE THREAD

**Issue by disambiguator** [tsconfig/bases#134]
Recent commits added ["tsconfig/next-strictest"](https://github.com/tsconfig/bases/blob/main/bases/next-strictest.json) and the documentation claims you can install it as so:
https://github.com/tsconfig/bases#nextjs-tsconfigjson

However, it is not actually published to NPM.
https://www.npmjs.com/search?q=%40tsconfig%2Fnext-strictest

**Comment by orta** [comment]
Looks like builds are failing: https://github.com/tsconfig/bases/actions/runs/3232148885/jobs/5292449678

**Comment by orta** [comment]
This was just deprecated, but I think it did deploy
