### ISSUE TITLE
Add Node.js v19 bases

### ISSUE THREAD

**Issue by nikolay** [tsconfig/bases#142]
After v19.0, now v19.1 of Node.js is out.

**Comment by orta** [comment]
Sure, you're welcome to look into it

**Comment by voxpelli** [comment]
Is there anything distinct that would differ from the Node 18 base?

**Comment by nikolay** [comment]
@voxpelli If there's no difference, it still should exist as a copy of v18.

**Comment by nikolay** [comment]
@orta This attitude is not productive. I'm not an expert of the Node.js ecosystem to be qualified to contribute a PR. Trust me, I contribute where I can add value to a multitude of open-source projects and I sponsor a bunch, too. But, okay, I will give it try.

**Comment by voxpelli** [comment]
@nikolay The work then is to figure that out

**Comment by orta** [comment]
Yep, asking folks interested in the work to do the work is realistically the only way I can handle the level of open source I maintain in my spare time. I just don't have time to put the hours in to do work which only benefits other folks. It's not blame or snark, its scale and a reminder this is a community project - anyone could take a look at it.

I wrote some notes in https://github.com/microsoft/TypeScript-wiki/blob/main/Node-Target-Mapping.md on how I keep track.
