### ISSUE TITLE
Refactor due to "extends": [] Array support

### ISSUE THREAD

**Issue by devinrhode2** [tsconfig/bases#148]
tsconfig.json files will soon support arrays inside the `"extends"` key:
https://github.com/microsoft/TypeScript/issues/29118

I'd imagine this will simplify this project a lot, and make creating typescript configurations much more expressive.

I believe it may be best to re-imagine `tsconfig/bases` given this new TS feature. I can't imagine migrating from the non-array based setup would be hard. Existing packages would still exist as published, but wouldn't receive any new updates (do they need to be updated?).

<sub>hype train: https://twitter.com/DevinRhode2/status/1602790036050681858</sub>

**Comment by orta** [comment]
I think it could allow some of them to be smaller, but hopefully the change may encourage more folks to ship their own tsconfigs too
