### ISSUE TITLE
Replace all `"importsNotUsedAsValues": "error"` by `"verbatimModuleSyntax": true`

### ISSUE THREAD

**Issue by acidoxee** [tsconfig/bases#160]
With the upcoming TS v5 release, `importsNotUsedAsValues` is being deprecated, and using it in a tsconfig file yields the following error:

```
error TS5101: Flag 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.
```

While the warning can be temporarily silenced, we'll eventually all have to drop that setting and use `verbatimModuleSyntax` instead. Do you think it would be a good idea to swap those settings now? I don't suppose this package follows semver since TS itself doesn't, so I'm guessing it shouldn't even be considered a problem to replace `importsNotUsedAsValues` with `verbatimModuleSyntax` in a new release soon?

Thanks 🙏

**Comment by orta** [comment]
Correct #148  - yeah, totally give it a shot! - this repo is a pretty simple set of deno scripts and I'm OK with manually running some of the deprecation commands into npm myself for some of the deps like `@tsconfig/node18-strictest`

**Comment by acidoxee** [comment]
Here you go @orta: https://github.com/tsconfig/bases/pull/161. I do hope this is what you had in mind, and I guess we should wait for the official TS v5 release before merging anything.

**Comment by Techn1x** [comment]
TS 5 released and I'm seeing this error now :)
