### ISSUE TITLE
Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5 for strictest cfg

### ISSUE THREAD

**Issue by unclamped** [tsconfig/bases#164]
After installing @tsconfig/strictest and trying to build with it, I get the following error:
`error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.`
Not much else to say, the deprecated option must be replaced or deleted.

**Comment by orta** [comment]
You're welcome to follow along in #160

**Comment by unclamped** [comment]
> You're welcome to follow along in #160

I didn't see the PR, thanks :)
