### ISSUE TITLE
node18 and strictest configs incompatibility

### ISSUE THREAD

**Issue by SkeLLLa** [tsconfig/bases#168]
**Environment**:
Node: 18
Typescript: 5.0.4

**Steps to reproduce**:

1. Create a simple project with typescript 5 and configs: `npm i -D @tsconfig/strictest @tsconfig/node18 typescript @types/node`
2. Create a `index.ts` file with following contents 
```ts
import { readFileSync } from 'node:fs';

export function test() {
  console.log(readFileSync('./index.ts'))
}
```
3. Use `tsconfig.json` from README:
```json
{
  "extends": ["@tsconfig/strictest/tsconfig", "@tsconfig/node18/tsconfig"]
}
```
4. Compile code using `tsc`

**Expected result**:

Code compiles without errors.

**Actual result**:

Code compilation fails with errors:

```
src/index.ts:1:10 - error TS1286: ESM syntax is not allowed in a CommonJS module when 'verbatimModuleSyntax' is enabled.

1 import { readFileSync } from 'node:fs';
           ~~~~~~~~~~~~

src/index.ts:3:1 - error TS1287: A top-level 'export' modifier cannot be used on value declarations in a CommonJS module when 'verbatimModuleSyntax' is enabled.

3 export function test() {
  ~~~~~~
```

**Extras**: 
Nether using `"type": "module"` in package.json, nor using `.mts` , `.cts` extensions not helping.

**Suggestions**:

- Maybe it worth to set `"verbatimModuleSyntax": false,` in all node* configs, unless they have `"module": "commonjs"`
- Move  `"verbatimModuleSyntax": true,` to `@tsconfig/esm`, since it doesn't works only with esm.

Related to #161

**Comment by xg4** [comment]
You can use @tsconfig/esm to fix it.

`tsconfig.json`

```json
{
  "extends": ["@tsconfig/strictest/tsconfig", "@tsconfig/node18/tsconfig", "@tsconfig/esm/tsconfig.json"]
}
```

```bash
npx tsc
# success
```

Without @tsconfig/esm, you can only use cjs.

```ts
const { readFileSync } = require('node:fs')

module.exports = function test() {
  console.log(readFileSync('./index.ts'))
}
```

**Comment by SkeLLLa** [comment]
Yes, esm fixes, since `verbatimModuleSyntax` can be used only with esm. So that's one of my suggestions was to move that `verbatimModuleSyntax` setting to esm configs from `stirctest`.

And actually by adding esm typescript will produce esm output, which I don't want to have.

**Comment by xg4** [comment]
If you want to obtain a CommonJS module output when compiling TypeScript code with `tsc`, you can use the `--module` option to specify the output module system. 

```bash
# Produces a CommonJS module
tsc --module commonjs
```

**Comment by orta** [comment]
> verbatimModuleSyntax setting to esm configs from strictest

Yeah, I think this is the right call, using strictest shouldn't imply you are using esm

**Comment by SkeLLLa** [comment]
@orta maybe it also worth mention somewhere in docs that that rule can be replaced by one from eslint:
```
"@typescript-eslint/consistent-type-imports": "error"
```

It forces same behavior as verbatimModuleSyntax and have eslint autofix as a bonus.
