### ISSUE TITLE
use "module": "node16" for node16+.json ?

### ISSUE THREAD

**Issue by TatsuyaYamamoto** [tsconfig/bases#185]
In TypeScript v4.7, `"module": "node16"` can now be set. I understand that this feature follows the behavior of ES modules in Node.js.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html

Does this feature make sense to change `"module"` to `"node16"` in node16+ .json?
If not, could you please tell me why?

**Comment by orta** [comment]
No, you can mix both bases "node16" and "esm" trivially - I'm not quite at a point to assume that most people want to be making ESM projects by default

**Comment by TatsuyaYamamoto** [comment]
Thank you for your answer! I understand the policy of tsconfg/base.

> I'm not quite at a point to assume that most people want to be making ESM projects by default

I agree with you.

Node.js module system’s default is still commonjs, and TypeScript's `"module": "node16"` is also transpiled as commonjs by default. If users want to use ES modules, they need to use `.mts`or set`"type": "module”`.

I didn't think `”module”: "node16”` will interfere with development of commonjs user and I suggested.

**Comment by orta** [comment]
Great points, I read up on the docs. I think the node16+ should switch to "module: node16" (And I think this _probably_ should count as a semver major?)

**Comment by TatsuyaYamamoto** [comment]
> I think the node16+ should switch to "module: node16"

I created #187!

> this probably should count as a semver major?

Yes. Even if setting Node.js to use ESM, TypeScript will output commonjs if `module: commonjs` is set in tsconfig.json.

**Comment by Kurt-von-Laven** [comment]
What would be the rationale for making a semver major bump? It was released as a patch version bump. I think it should have been a minor version bump since it adds ESM functionality in a largely backwards-compatible way, but it isn't worth a second release. In any case, I want to make sure the patch release was intentional.

**Comment by orta** [comment]
It forces people to update TypeScript
