### ISSUE TITLE
vite-react - "moduleResolution": "bundler" error

### ISSUE THREAD

**Issue by mikeyamato** [tsconfig/bases#189]
## Issue

I'm running into a compile error that exists within the node_modules. Specifically, `../../node_modules/@tsconfig/vite-react/tsconfig.json:16:25 - error TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node12', 'nodenext'.`.

**package:** [@tsconfig/vite-react](https://www.npmjs.com/package/@tsconfig/vite-react)

**version**: 2.0.0

<img width="1196" alt="Screenshot 2023-05-10 at 4 13 29 PM" src="https://github.com/tsconfig/bases/assets/27756216/1e09efbb-00a1-41ad-83a4-eb4e14f13108">

## Resolution

Replace `bundler` with one either `node` or `classic`.

**Comment by orta** [comment]
Sounds like you're running on an older version of TypeScript, you can use the 1.x branch of vite-react for that 👍🏻
