### ISSUE TITLE
Add node 14

### ISSUE THREAD

**Issue by orta** [tsconfig/bases#2]

**Comment by orta** [comment]
its all green on https://kangax.github.io/compat-table/es2016plus/

**Comment by BenjD90** [comment]
+1 to add this :smile:

**Comment by orta** [comment]
Want to take a look at figuring it out?

**Comment by BenjD90** [comment]
I think that the tsconfig for Node 14 could be something like this :

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Node 14",
  "compilerOptions": {
    "lib": ["es2019", "es2020"],
    "module": "commonjs",
    "target": "es2020",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }  
}
```

@orta What do you think about this ?

**Comment by orta** [comment]
It could be it - Did you verify the features in es2019 / es2020 are available inside that version of node?

**Comment by BenjD90** [comment]
yes, it's all in the page you linked before : https://kangax.github.io/compat-table/es2016plus/

To be complete, more details are available [here](https://node.green/#ES2020) :
![image](https://user-images.githubusercontent.com/8216338/94155285-0f58c900-fe7f-11ea-8c20-51021fc95d7b.png)

ES2019 is already supported in Node 12 ;) :
https://github.com/tsconfig/bases/blob/master/bases/node12.json

**Comment by BenjD90** [comment]
And, by the way, all ESNEXT at Stage 3 are supported too : https://node.green/#ESNEXT

**Comment by orta** [comment]
Great, agree - want to ship a PR to claim the credit?

**Comment by BenjD90** [comment]
Ok, I'll try to do the PR this evening, on 1-2 hours :wink: 

thanks

**Comment by BenjD90** [comment]
Here's the PR #36

**Comment by BenjD90** [comment]
@orta is it possible to publish `@tsconfig/node14` ?

**Comment by orta** [comment]
It should auto publish overnight, if it doesn't that's a bug!

**Comment by orta** [comment]
It did https://github.com/tsconfig/bases/runs/1163996333?check_suite_focus=true#step:6:17

**Comment by cowwoc** [comment]
Hi,

Your config disagrees with https://stackoverflow.com/a/61305579/14731. Who is right?

**Comment by LinusU** [comment]
Hey, author of https://stackoverflow.com/a/61305579/148072 here 👋 

Since Node.js 14 supports ES Modules, I wanted to take advantage of that. That's why it uses `"module": "ES2020"` & `"moduleResolution": "node"`, instead of `"module": "commonjs"`.

I wouldn't say that anyone is right or wrong! It depends on wether you want to stick with `require('...')` for a while longer, or start using `import _ from _` even though it's still quite new to Node.js...

**Comment by orta** [comment]
Nice write-up in that SO Linus! 

TS's support of the node implementation of ESM isn't complete enough that we class it as a feature in TypeScript yet - but when we do, I think we can ship a separate `node14-esm` base for folks to work from 👍🏻

**Comment by LinusU** [comment]
@orta Thanks!

> TS's support of the node implementation of ESM isn't complete enough that we class it as a feature in TypeScript yet

Is this documented somewhere? 🤔 or is there anything in particular that doesn't work?

**Comment by SleepyCatGuy** [comment]
does node 14 base work with node 15?

**Comment by orta** [comment]
Node 14 is in, so I'm closing this
