### ISSUE TITLE
Understanding Versioning of TSConfigs

### ISSUE THREAD

**Issue by stuft2** [tsconfig/bases#203]
I would like to understand how these configurations are being versioned. It seems that every so often a change is made that breaks my code. For example, the change from `module: commonjs` to `module: Node16` in all the node configurations. I was using those configurations to compile specifically to commonjs but after a minor version update, all my code is compiling to Node16 syntax. Should I be locking on an exact version of my configuration?

**Comment by orta** [comment]
You should always be locking your dependencies regardless and updating them when you're OK with handling the changes, but we did do a major version bump for all those that we could for it to indicate the change as mentioned in the README:

> We target the latest versions stable version of TypeScript, note that because we want to be consistent with the versioning the target runtime we can't always do semver releases.

You're welcome to read https://github.com/tsconfig/bases/pull/197 to understand why
