### ISSUE TITLE
inconsistent case for "module" field in node bases

### ISSUE THREAD

**Issue by dominikg** [tsconfig/bases#209]
According to https://www.typescriptlang.org/tsconfig#module lowercase `node16` is allowed, but node bases for node16 and up use upperfist Node16 here.

PS. bases for versions older than 16 (12, 14) use `node16`, which is lowercase but also kind of surprising, given that they use something more recent than the node version they should be used with/for.

**Comment by dominikg** [comment]
http://json.schemastore.org/tsconfig has an enum with uppercase Node16 in it, but also a pattern that spells `[Nn][Oo][Dd][Ee]16` so `nODe16` would be fine? wth

**Comment by orta** [comment]
I'm pretty sure TypeScript will lowercase the values, which makes any case acceptable

**Comment by dominikg** [comment]
I just noticed it due to a testcase failing while trying to update tsconfck to node18 (it expected lowercase like in the node14 base).  Might end up refactoring the tests to use snapshots per node version and not use a public base to avoid this issue in the future.

The inconsistencies between the official bases, official json schema and official documentation would be my answer to the "why not" question. Even the internal structures are not all the same (eg node vs node10). Isn't the goal of typescript to improve consistency and avoid problems like this?
