### ISSUE TITLE
missing settings in @tsconfig/strictest

### ISSUE THREAD

**Issue by brodybits** [tsconfig/bases#219]
~~I think the following items are missing and should be set to `true` to `@tsconfig/strictest`:~~

__CORRECTED: these ARE documented to follow the `strict` configuration item by default:__

- [`noImplicitAny`](https://www.typescriptlang.org/tsconfig#noImplicitAny)
- [`noImplicitThis`](https://www.typescriptlang.org/tsconfig#noImplicitThis)
- [`useUnknownInCatchVariables`](https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables)

---

I found this article which I think could be a nice reference for this: https://www.lucaspaganini.com/academy/20-typescript-compiler-options-for-your-tsconfig-json

~~Of course it should be quite straightforward for me or someone else to contribute this kind of update. I would be happy to contribute this when I get a spare moment for this.~~

**Comment by jakebailey** [comment]
Those are all already implied by `"strict": true`, so don't need to be configured.

**Comment by brodybits** [comment]
> Those are all already implied by `"strict": true`, so don't need to be configured.

My bad, that is correct by default as documented in each of the options - just updated the description.

I think the following text in <https://www.typescriptlang.org/tsconfig#strict> is both incorrect & confusing:

<blockquote>
Turning this on is equivalent to enabling all of the <em>strict mode family</em> options, which are outlined below.
</blockquote>

Hope we can get this fixed or clarified, someday.
