### ISSUE TITLE
Add `javascript.json`

### ISSUE THREAD

**Issue by TatsuyaYamamoto** [tsconfig/bases#222]
This issue is a propose to add new base.

`javascript.json` has 2 options.

```
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
  }
}
```

## Motivation

Related: #218 

In #218, I understood this repo's intention that `strictest.json` has `checkJs` and no `allowJs`.

On the other hands, I counld not know this intention from README.md and `strictest.json`.  I think it’s good to add comments to `strictest.json` to tell that you can choose `allowJs`, but if it's assumed that `strictest.json`’s target is ts files only, I think `checkJs` should be defined in other than `strictest.json`.

So, I propose `javascript.json` to apply any compilerOptions to js file .

**Comment by orta** [comment]
I'm not wild on this TBH, we're mostly focused on runtimes in this repo and choosing to use JS is really an application choice - showing you want to use JS support is something you want someone to know when they read the root tsconfig.json (or you can use a jsconfig.json to imply that )

**Comment by TatsuyaYamamoto** [comment]
thank you for your response! I close this PR
