### ISSUE TITLE
Remix: the `baseUrl` in `remix/tsconfig.json` is useless

### ISSUE THREAD

**Issue by fedemp** [tsconfig/bases#223]
The `baseUrl` in https://github.com/tsconfig/bases/blob/main/bases/remix.json does not do any good (or bad) cause a project has to include `"baseUrl": "."` in its own `tsconfig.json` for file resolution to work.

Raising this cause having this property in the bases makes it as if it configuring it in the project was not needed.

**Comment by orta** [comment]
Might need to add a way to add docs to the README implying that you need to set this in your tsconfig

**Comment by dani-mp** [comment]
Thanks @fedemp for this, I was getting crazy! 😭
