### ISSUE TITLE
`@tsconfig/esm` is deprecated in README, but v1.0.5 has been just released

### ISSUE THREAD

**Issue by kachkaev** [tsconfig/bases#225]
👋 folks! I just saw an update of `@tsconfig/esm` which I thought to be deprecated: https://github.com/kachkaev/website/pull/206

Seems like the latest version is not, [according to npm](https://www.npmjs.com/package/@tsconfig/esm?activeTab=versions):
![Screenshot 2023-10-07 at 12 29 10](https://github.com/tsconfig/bases/assets/608862/f624c8ae-59ab-4eb9-9ae6-549ee9cf848a)

README.md still advises against using this package:

https://github.com/tsconfig/bases/blob/a1bf7c0fa2e094b068ca3e1448ca2ece4157977e/README.md?plain=1#L372-L374

What is the current status of this package?

**Comment by orta** [comment]
no idea why that deployed ([but it did](https://github.com/tsconfig/bases/actions/runs/6438931552/job/17486027230)), there's not been any changes to this repo in weeks

**Comment by orta** [comment]
It's deprecated now, and I'll remove it from this repo entirely so this doesn't happen again
