### ISSUE TITLE
Remove noEmit from `Create React App`

### ISSUE THREAD

**Issue by FreePhoenix888** [tsconfig/bases#226]

**Comment by jakebailey** [comment]
noEmit is required to use bundler module resolution. CRA bundles and does not need tsc emit.

**Comment by FreePhoenix888** [comment]
This issue closed cause of this [enlightment](https://github.com/tsconfig/bases/issues/38#issuecomment-1752114210). 
https://github.com/tsconfig/bases/issues/227 is opened instead
