### ISSUE TITLE
Reasoning behind removing the ESM config

### ISSUE THREAD

**Issue by matthewlilley** [tsconfig/bases#228]
Discussions aren't enabled on this repo or I would've asked that there.

What was the reasoning behind removing the ESM config?

TIA

**Comment by orta** [comment]
You can read up on  https://github.com/tsconfig/bases/pull/197 but generally there is no "ESM" runtime, only something like "Node"

**Comment by matthewlilley** [comment]
Gotcha, I was trying to find a relevant PR but couldn't. Thanks for the help!
