### ISSUE TITLE
Add bundler config

### ISSUE THREAD

**Issue by vladshcherbin** [tsconfig/bases#229]
Hi 👋 

I'm using node v20 and [tsx](https://github.com/esbuild-kit/tsx)

`@tsconfig/node20` has `module` set to `node16` so imports without extensions are not supported. `tsx` has support for such imports. According to [handbook guide](https://www.typescriptlang.org/docs/handbook/modules/reference.html#es2015-es2020-es2022-esnext) it's advised to use `esnext` and `bundler` with `tsx`, bun and other bundlers.

Does it make sense to create a simple base config for bundlers?

```
"module": "esnext"
"moduleResolution": "bundler"
```

It would make possible to use it this way:

```json
{
  "extends": [
    "@tsconfig/node20",
    "@tsconfig/bundler"
  ]
}
```

**Comment by orta** [comment]
I don't think so, I think that your runtime is node but that your specific app uses the bundler resolution - so having that in your tsconfig is showing the right information about your specific project (instead of hiding it in a shared bundler tsconfig)

**Comment by vladshcherbin** [comment]
Good to know, I was a bit confused after reading multiple issues on TS module resolution configuration. Thank you for the clarification.

Hopefully this will also be helpful for other devs having the same question 🙌
