### ISSUE TITLE
Feature Request: Add a Dedicated Node ESM Configuration

### ISSUE THREAD

**Issue by bennoinbeta** [tsconfig/bases#233]
### Description

As ECMAScript modules (ESM) are becoming the standard for JavaScript and more Node.js packages are moving to ESM only (e.g., [chalk](https://github.com/chalk/chalk)), it would be beneficial to have a TypeScript configuration specifically tailored for Node.js projects that use and target ESM.

Pure ESM Package:
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

### Feature Request

I propose adding a new base configuration called `node-esm-lts` (or a similar name) that sets up TypeScript compiler options optimized for Node.js projects that are ESM-based

### Suggested `tsconfig.json` settings for `node-esm-lts` based on `node-lts`

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Node ESM LTS",
  "_version": "18.1.0",
  "compilerOptions": {
    "lib": ["es2023"],
    "module": "esnext",
    "target": "es2022",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node"
  }
}
```

**Comment by bennoinbeta** [comment]
> These aren't the right settings for Node ESM; that would be Node16 or NodeNext. You definitely do not want to be using esnext for Node
> 
> (The Typescript website has all new docs on modules and module configuration; you may want to peruse https://www.typescriptlang.org/docs/handbook/modules/introduction.html)

thanks for the notice, the suggested config was just quickly created as idea without much research :) What config would you suggest so that I can use pure `esm` packages without dealing with async inline require  🤷‍♂️ Thanks :)

**Comment by jakebailey** [comment]
All of the node configs this repo have should already set `node16` (e.g. https://github.com/tsconfig/bases/blob/main/bases/node20.json#L8); if you're really targeting Node, then you sould either put ESM code into `.mjs` files, or set `type=module` in `package.json` and can put ESM into `.js` files. This ensures that when you build, the outputted files will work in Node.

**Comment by bennoinbeta** [comment]
> All of the node configs this repo have should already set `node16` (e.g. https://github.com/tsconfig/bases/blob/main/bases/node20.json#L8); if you're really targeting Node, then you sould set `"type": "module"` in `package.json` and put ESM into `.js` files, or use `.mjs` files (which are always ESM). Either ensures that when you build, the outputted files will work in Node.

ok thanks for the intel :) I'll give that a try and dive deeper into the topic. Will close the issue for now and reopen if I see fit after me research. Thanks @jakebailey for the notices :)
