### ISSUE TITLE
Confused - why is this marked as deprecated on npm?

### ISSUE THREAD

**Issue by magicmark** [tsconfig/bases#235]
On install, we see the following message:

```
npm WARN deprecated @tsconfig/node18-strictest@1.0.0: TypeScript 5.0 supports combining TSConfigs using array syntax in extends
```

I'm unclear as to what action i'm supposed to take here - this seems to imply that this package is deprecated and no longer necessary - but that doesn't make sense - how would i refer to the config in my tsconfig.json?

What should an example config look like?

**Comment by magicmark** [comment]
Oh i see - you're just supposed to install them separately now - cool!

https://github.com/tsconfig/bases#what-about-combined-configs

(Might be worth clarifying in the deprecation message?)

**Comment by orta** [comment]
I think this is fine, we have docs in the README as you've linked, thanks
