### ISSUE TITLE
Question: Why  are `es2015` and `commonjs` recommended

### ISSUE THREAD

**Issue by zanminkian** [tsconfig/bases#256]
```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```
I have a question about `@tsconfig/recommended`. Why are `es2015` and `commonjs` recommended?
- 2015 is almost ten years ago. 
- ESM is better than commonjs. 

Furthermore, I don't know the use cases for `@tsconfig/recommended`. Is there any possible to deprecate it?

**Comment by orta** [comment]
Because those are the recommendations we made in `tsc --init` and `@tsconfig/recommended` is based on that, if TypeScript updates the initial template - then so can this base!

**Comment by zanminkian** [comment]
After running `npx tsc --init`, the `target` is `es2016` now (ts 5.0+).
