### ISSUE TITLE
"strictest" includes non-typesafety relevant options

### ISSUE THREAD

**Issue by domdomegg** [tsconfig/bases#262]
Going with the definition that strictest "automatically enables every TypeScript compiler flag that has to do with type checking, making it as strict as possible.", I think the following should be out of scope given that these do not detect type errors - and are more just general linting rules (i.e. violations of these alone will never lead to a runtime error):

- allowUnreachableCode
- allowUnusedLabels
- noPropertyAccessFromIndexSignature
- noUnusedLocals
- noUnusedParameters

Also see #156. I think this is a separate discussion: that discussion foucses on build-related flags and logistics around how the configs are used. This issue relates to specific flags that aren't performing type checking.

--

Proposed solutions:
- Removing these flags from strictest
- Creating a new preset, maybe `strictest-types` which has all the type checking rules enabled (but not these extra rules about e.g. unused code)

**Comment by orta** [comment]
No, I think these are the "strictest" version of TypeScript - you're welcome to a differing opinion but I don't think we need to make breaking changes to strict to remove the linter-ish properties only to eventually have to remake a version a bit like this.
