### ISSUE TITLE
Module name '@typescript/lib-es2022/string' was not resolved.

### ISSUE THREAD

**Issue by vaynevayne** [tsconfig/bases#263]
<img width="809" alt="image" src="https://github.com/tsconfig/bases/assets/124666577/e9f5219c-90c4-4983-ac47-67a4f5aa7d94">

**Comment by orta** [comment]
Not an issue with this repo, this is a native typescript feature - https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#supporting-lib-from-node_modules
