### ISSUE TITLE
dynamic imports create a double default-wrapped export - e.g. `{ default: { default: Foo } }`

### ISSUE THREAD

**Issue by magicmark** [tsconfig/bases#273]
### Repro

Runnable repro: https://stackblitz.com/edit/markl-ts-jest-repro-gbovnq?file=README.md

Relevant files:

**`foo.ts`**
```javascript
export default function MyFoo() {
  return 'foo';
}
```

**`bar.ts`**
```javascript
(async function main() {
  const foo = await import('./foo.js');
  console.log(foo);
})();
```

**`tsconfig.json`**
```
{
  "extends": ["@tsconfig/node20/tsconfig.json"],
  "include": ["src/**/*"]
}
```

### Actual vs Expected behavior

```javascript
const foo = await import('../src/foo');
console.log(foo);
```

This produces the following output:

```
[Module: null prototype] {
  __esModule: true,
  default: { default: [Function: MyFoo] }
}
```

Expected behavior is that it produces the following output:

```
[Module: null prototype] {
  __esModule: true,
  default: [Function: MyFoo]
}
```

(stackblitz runs on node 18, but this reproduces exactly on LTS (20) as well)

Thanks!

**Comment by jakebailey** [comment]
This has nothing to do with the tsconfig bases project, which is just shorthand for existing TS configs.

**Comment by magicmark** [comment]
@jakebailey understood but dynamic imports are stage 4 - I would expect this to be supported out of the box.

So my issue here specifically is - should the node ts configs be configured to support dynamic imports?

**Comment by jakebailey** [comment]
It is configured to do that, but this is a runtime issue with TypeScript's CJS import helpers, so the issue should be files on TypeScript. This repo is just shorthand for copying a recommended tsconfig and isn't the right place to ask about this.

**Comment by magicmark** [comment]
@jakebailey ack thanks https://github.com/microsoft/TypeScript/issues/59257
