### ISSUE TITLE
node 22 has Iterator helpers but TS with the node 22 config is throwing errors

### ISSUE THREAD

**Issue by acommodari** [tsconfig/bases#282]
As the title says it seems with the current target/lib I cant use iterator helpers even though TS 5.6 and node 22 supports them

**Comment by SoulKa** [comment]
It also seems that the `@tsconfig/node22` using `es2023` as lib does not include `Array.fromAsync()` which is actually officially supported since node 22: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fromAsync#browser_compatibility

**Comment by orta** [comment]
no tsconfig bases should use `esnext` libs, they need to wait until it's been moved into a concrete year `.d.ts`

I'm not up-to-date on the shipped dts files though I'm afraid

**Comment by SoulKa** [comment]
I'm confused. Shouldn't this tsconfig represent the available methods in node 22? Because node 22 has `Array.fromAsync()`. However, this is not in `"es2023"` but can be included by `"ESNext.Array"`.

**Comment by jakebailey** [comment]
If anything the node types can copy the declarations so they're there ahead of time (they did this for .at). Including esnext is definitely a no-no.

**Comment by acommodari** [comment]
Sorry if this was already mentioned somewhere else but how do you determine the target? 
Seems like node 18/20/22 have been stuck on es2022 but in previous LTS versions target was continuously bumped by one. 
Node is continuing to pull in New V8 versions on each release so we should be relatively up to date

**Comment by orta** [comment]
you can use node.green to determine what ES20XX is classed as being a version node supports - then you apply some nuance to "are the things it doesn't do enough to warrant the downlevel"

**Comment by acommodari** [comment]
So looking at node.green its feasible that node 22 target could be set as high as es2024 when TS 5.7 is released?
seems like only 1 regex feature in es2022 is missing and a unicode update in es2024 🤔

**Comment by acommodari** [comment]
even node 20 to an extent could move to es2023 at least is the regex feature the reason lib and target have been out of sync in recent lts configs?

**Comment by jakebailey** [comment]
I do not think it's a good idea to bump the target/lib for minor releases of node. You may choose to install `@tsconfig/node22`, and then a user runs your code with a lower minor version. This is not unusual, especially for things like "I am writing a GitHub action and have to target any runner that could have existed".

It's very easy to override yourself if you know better.
