### ISSUE TITLE
Consider skipLibCheck to false

### ISSUE THREAD

**Issue by romainPrignon** [tsconfig/bases#34]
Hi there

I Love the idea of sharing tsconfig file. Great idea.
I can see in the recommended `tsconfig.json` that skipLibCheck is set to `true`.

Do we really want to enforce that behaviour ?
As I can see here:
- https://www.typescriptlang.org/tsconfig#skipLibCheck
- https://stackoverflow.com/questions/52311779/usage-of-the-typescript-compiler-argument-skiplibcheck
- https://www.reddit.com/r/typescript/comments/aa3ui7/question_why_skiplibcheck_true_is_not_the_default/

There is pros in day to day coding but cons in the long term

**Comment by orta** [comment]
Yep, it's what we do with `tsc - - init`

**Comment by agilgur5** [comment]
For reference, I've linked to a few of the related issues/PRs on the topic here: https://github.com/microsoft/TypeScript-Website/pull/970#issue-472956269

**Comment by orta** [comment]
Thanks @agilgur5 👍🏻
