### ISSUE TITLE
Add Next.js base

### ISSUE THREAD

**Issue by kripod** [tsconfig/bases#35]
Based on the list of [available](https://github.com/vercel/next.js/blob/canary/packages/next-polyfill-nomodule/src/index.js) and [omitted](https://github.com/vercel/next.js/pull/15772) polyfills, a base config could be made for Next.js projects. This would make sure that no compatibility issues arise during runtime in older browsers.

**Comment by orta** [comment]
I talked to the folks at vercel team about this, they were considering embedding the same thing but inside the next dependency itself

**Comment by orta** [comment]
This is in
