### ISSUE TITLE
Add a react base?

### ISSUE THREAD

**Issue by mgcrea** [tsconfig/bases#38]
Since this repo has a base for react-native, it might make sense to have one for react web?

Using `npx create-react-app my-app --template typescript` you end up with the following config, could be a good start for a base:

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}
```

**Comment by orta** [comment]
We could make it more fine-grained and have a 'create-react-app'  base? I think that makes a lot of sense

**Comment by mgcrea** [comment]
Yep a `create-react-app` base would be more correct indeed 👍 .

**Comment by aladdin-add** [comment]
seem it has been fixed by #39

**Comment by aladdin-add** [comment]
@orta can you release a new version - I didn't find it in npm.

**Comment by orta** [comment]
Shipped! https://github.com/tsconfig/bases/runs/1748184408?check_suite_focus=true#step:6:15 - had to fix the jsonc parser for newer deno releases

**Comment by aladdin-add** [comment]
thanks, I've tried the package, but got
```bash
error TS18003: No inputs were found in config file '/Users/weiran/repo/dian/honor/tsconfig.json'. Specified 'include' paths were '["node_modules/@tsconfig/create-react-app/src"]' and 'exclude' paths were '[]'.
```

it was fixed by adding `include: ["src"],` in project `tsconfig.json`

**Comment by orta** [comment]
Cool, want to send a PR for that?

**Comment by aladdin-add** [comment]
sure, will make a PR later. :)

**Comment by FreePhoenix888** [comment]
Why is noEmit used here?

**Comment by orta** [comment]
it is in the create react app default - I'd say its very likely you are using a bundler if you are using react, and probably aren't using tsc to emit your JS. Seems like a reasonable default to me.

**Comment by FreePhoenix888** [comment]
> it is in the create react app default - I'd say its very likely you are using a bundler if you are using react, and probably aren't using tsc to emit your JS. Seems like a reasonable default to me.

You are right. I was wondering why that tsconfig is named "create-react-app" instead of "react". Now I understand. thank you!
