### ISSUE TITLE
Support for bumping to specific package versions

### ISSUE THREAD

**Issue by dummdidumm** [tsconfig/bases#42]
I'm currently exploring how to get rid of the `"types": ["svelte"]` entry in Svelte's tsconfig base. Doing this would be a breaking change, `@tsconfig/svelte` would need to be bumped to `2.0.0` if that (not-yet-created) PR would get merged. Is this possible with the current infrastructure? If so, how to accomplish it? If not, how would adding this look like?

**Comment by orta** [comment]
Hrm, it's not. 

Maybe we can strip any $ keys from the json files and support a `$version: "2.0"` or something, and the patch is set up automatically?

**Comment by dummdidumm** [comment]
Looking at the source it's `display`, not `$display`. Also, `$schema` starts with `$` and should be kept, right? So maybe `_` instead. Apart from that this sounds like a nice idea. Logic then could be
1. get and remove `_version`
2. check if version is higher than current. If yes, use it. If no, bump minor of current

**Comment by orta** [comment]
Yep `_` makes sense 👍🏻
