### ISSUE TITLE
@tsconfig/next is not published

### ISSUE THREAD

**Issue by hnordt** [tsconfig/bases#63]
Hey!

First of all, thank you for this amazing project!

---

```sh
➜ npm install --save-dev @tsconfig/next

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tsconfig%2fnext - Not found
npm ERR! 404 
npm ERR! 404  '@tsconfig/next@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hnordt/.npm/_logs/2021-06-06T17_07_42_807Z-debug.log
```

**Comment by connorjs** [comment]
Also thank you for the great project and the active efforts. Maybe @phuctm97 can comment on this? It seems related to #61 (ec453e78654c65236bccf6e30a5256bf5618531)

**Comment by phuctm97** [comment]
Need @orta comments on this. I actually asked him in the PR, look like `deploy` CI doesn't probably publish the new package `@tsconfig/next`.

**Comment by connorjs** [comment]
Thanks! I now see that 208ebe11e6327201d5310bbf0ecd66aae5f3cbaf introduced the actual config (#60 ). I'll mimic that file locally until the publish 😄

**Comment by hnordt** [comment]
@phuctm97 `nuxt` is also not published: https://www.npmjs.com/package/@tsconfig/deno

**Comment by phuctm97** [comment]
@orta Please help. Looks like the `deploy` CI is not working for new packages?

**Comment by orta** [comment]
Thanks folks, I've revised the deploy infra in https://github.com/tsconfig/bases/pull/65 and that's shipped all the missing versions - https://github.com/tsconfig/bases/runs/2782106114?check_suite_focus=true
