### ISSUE TITLE
#55 should be documented

### ISSUE THREAD

**Issue by AcrylicShrimp** [tsconfig/bases#66]
Hello! Thanks for this great package.

I have an project that uses `@tsconfig/svelte@1.0.10`. After upgrading it to `@tsconfig/svelte@2.0.1`, it fails to compile.

```
ERROR in D:\Devel\Projects\devlog\devlog-web\app\index.ts
./app/index.ts 3:16-30
[tsl] ERROR in D:\Devel\Projects\devlog\devlog-web\app\index.ts(3,17)
      TS2307: Cannot find module './App.svelte' or its corresponding type declarations.
ts-loader-default_e3b0c44298fc1c14
```

Here's the diff between the `@1.0.11` and the `@2.0.1`. As you can see, the `types` property is gone.

```diff
--- a/1.0.11.json
+++ b/2.0.1.json
@@ -16,8 +17,6 @@
       enable source maps by default.
      */
     "sourceMap": true,
-    /** Requests the runtime types from the svelte modules by default. Needed for TS files or else you get errors. */
-    "types": ["svelte"],

     "strict": false,
     "esModuleInterop": true,
```

Is it intended or bug? Should I stick to `@1.0.10`?

I'm wonder it might help but below are the packages I'm using.
- `typescript@4.3.5`
- `webpack@5.42.0`
- `svelte-loader@3.1.2`
- `svelte-preprocess@4.7.3`

Thank you.

### EDIT

After some searching, I found that it's intended and a workaround is already mentioned #55 . And I think it should be documented somewhere. I'm sorry for bothering.

**Comment by orta** [comment]
Happy to take PRs figuring out a good way to document these sort of things 👍🏻

**Comment by raitono** [comment]
Should this be closed now that the above PR has been merged?

**Comment by AcrylicShrimp** [comment]
Yes!
