### ISSUE TITLE
Combined bases as a workaround for tsconfig.json `extends` limitations

### ISSUE THREAD

**Issue by jonahsnider** [tsconfig/bases#89]
Following the addition of the "strictest" config there is now [an issue](https://github.com/microsoft/TypeScript/issues/29118) for users who want to use "strictest" and another base from this repo (ex. "node16").

Could an additional script be added to generate combined bases?

ex. given the input of

```json
[
	["strictest", "node16", "esm"],
	["strictest", "node16"]
]
```

output the bases

- `strictest-node16-esm/tsconfig.json`
- `strictest-node16/tsconfig.json`

Where "strictest-node16-esm` is defined as "esm" (a potential new base, see #76) extends "node16" extends "strictest".

**Comment by orta** [comment]
Good idea.

Yep, I agree we should do these, and I think that is a good tactic. I think it should go `[platform]-[additions]-[...additions]` (so `node16-esm-strictest` or `node16-strictest-esm`, I don't mind either)

I feels right to document them as secondary in the repo README e.g. something like this:

### Node 16 <kbd><a href="./bases/node16.json">tsconfig.json</a></kbd>

Install:

```sh
npm install --save-dev @tsconfig/node16
yarn add --dev @tsconfig/node16
```

Add to your `tsconfig.json`:

```json
"extends": "@tsconfig/node16/tsconfig.json"
```

Also available as [`node16-esm-strictest`](npmlink) .

**Comment by jonahsnider** [comment]
I'll try playing around with ways to implement this later today.
I plan to just `Object.assign` the bases together since using `extends` itself is very unpleasant (relies heavily on the file system and npm dependencies).
I think this is fine for UX as long as there is a note in the README to explain how the combined base was generated.

**Comment by orta** [comment]
Yep, I think that's the right idea
